name: bookstore

services:
  app:
    build:
      context: ./docker/php-fpm/
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    restart: always
    depends_on:
      - mysql

  nginx:
    build:
      context: ./docker/nginx/
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:80"
    depends_on:
      - app

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookstore
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_general_ci
    volumes:
      - ./docker/mysql:/var/lib/mysql